CustomerSite/Models/ErrorViewModel.cs
namespace CustomerSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CustomerSite/Models/Repositories/CustomerApiRepository.cs
using BikeRentalApi.Models;
using BikeRentalApi.Models.Repositories;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace CustomerSite.Models.Repositories
{
    public interface ICustomerApiRepository : IRepositoryAsync<Customer>
    {
        Task<Customer> GetByEmailAsync(string email);
    }

    public class CustomerApiRepository : ApiRepository<Customer>, ICustomerApiRepository
    {
        public CustomerApiRepository(IHttpClientFactory clientFactory)
            : base(clientFactory) { }

        public async Task<Customer> GetByEmailAsync(string email)
        {
            using HttpResponseMessage response = await client
                .GetAsync($"{BikeRentalRoute.CustomersByEmail}/{email}");
            return await DeserializeFromResponse<Customer>(response);
        }
    }
}

CustomerSite/Models/Repositories/ReservationApiRepository.cs
using BikeRentalApi.Models;
using BikeRentalApi.Models.Repositories;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace CustomerSite.Models.Repositories
{
    public interface IReservationApiRepository : IRepositoryAsync<Reservation>
    {
        Task<Reservation> GetByBikeId(int id);
    }

    public class ReservationApiRepository : ApiRepository<Reservation>, IReservationApiRepository
    {
        public ReservationApiRepository(IHttpClientFactory clientFactory)
            : base(clientFactory) { }

        public async Task<Reservation> GetByBikeId(int id)
        {
            using HttpResponseMessage response = await client
                .GetAsync($"{BikeRentalRoute.ReservationsByBikeId}/{id}");
            return await DeserializeFromResponse<Reservation>(response);
        }
    }
}

CustomerSite/Controllers/HomeController.cs
using BikeRentalApi.Models;
using CustomerSite.Models;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Repositories;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace CustomerSite.Controllers
{
    public class HomeController : Controller
    {
        readonly IRepositoryAsync<Bike> _bikesRepo;
        readonly IRepositoryAsync<BikeStore> _bikeStoresRepo;

        public HomeController(IRepositoryAsync<Bike> bikes,
            IRepositoryAsync<BikeStore> bikeStores)
        {
            _bikesRepo = bikes;
            _bikeStoresRepo = bikeStores;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Bike> bikes = await _bikesRepo.GetAsync(BikeRentalRoute.Bikes);

            foreach (Bike bike in bikes)
                bike.OwningStore = await _bikeStoresRepo
                    .GetAsync(bike.OwningStoreId, BikeRentalRoute.BikeStores);

            return View(bikes);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CustomerSite/Controllers/ReservationController.cs
using BikeRentalApi.Models;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Repositories;
using Services.Reservations;
using System.Threading.Tasks;

namespace CustomerSite.Controllers
{
    public class ReservationController : Controller
    {
        readonly IReservationService _reservationService;
        readonly IRepositoryAsync<Bike> _bikesRepo;

        public ReservationController(IReservationService reservationService,
            IRepositoryAsync<Bike> bikes)
        {
            _reservationService = reservationService;
            _bikesRepo = bikes;
        }

        public async Task<IActionResult> Index(int id)
        {
            Bike requestedBike = await _bikesRepo.GetAsync(id, BikeRentalRoute.Bikes);

            if (requestedBike == null)
                return NotFound();

            return View(requestedBike);
        }

        [HttpPost]
        public async Task<IActionResult> CreateReservation(ReservationRequest reservationRequest)
        {
            // Refresh page if model validation fails
            if (!ModelState.IsValid)
            {
                TempData["InvalidSubmit"] = true;
                return RedirectToAction(nameof(Index), reservationRequest.RequestedBikeId);
            }

            // Create a reservation and move to confirmation page
            Reservation createdReservation = await _reservationService
                .CreateReservationAsync(reservationRequest);

            return View("ReservationConfirmed", createdReservation);
        }
    }
}

CustomerSite/ViewComponents/AvailabilityCheckViewComponent.cs
using BikeRentalApi.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Extensions;
using Services.Repositories;
using System.Threading.Tasks;

namespace CustomerSite.ViewComponents
{
    public class AvailabilityCheckViewComponent : ViewComponent
    {
        readonly IRepositoryAsync<Reservation> _reservationsRepo;

        public AvailabilityCheckViewComponent(IRepositoryAsync<Reservation> reservations)
        {
            _reservationsRepo = reservations;
        }

        public async Task<IViewComponentResult> InvokeAsync(int bikeId)
        {
            Reservation reservation = await _reservationsRepo.GetByBikeIdAsync(bikeId);
            return View(reservation);
        }
    }
}

CustomerSite/ViewComponents/ReservationFormViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Reservations;

namespace CustomerSite.ViewComponents
{
    public class ReservationFormViewComponent : ViewComponent
    {
        public ReservationFormViewComponent()
        {
        }

        public IViewComponentResult Invoke(int bikeId)
        {
            var request = new ReservationRequest
            {
                RequestedBikeId = bikeId
            };

            return View(request);
        }
    }
}

CustomerSite/Views/Home/Index.cshtml
@model IEnumerable<Bike>
@{
    ViewData["Title"] = "Welcome";
}

<div class="text-center">

    @if(Model.Any())
    {
    <h1 class="display-4 pb-4">Welcome!</h1>
    <h3 class="text-left">Browse</h3>
    <table class="table table-bordered table-hover text-left">
        <thead class="thead-dark">
            <tr>
                <th scope="col">
                    <div class="dropdown show">
                        <a class="btn btn-secondary dropown-toggle"
                           href="#" role="button" data-toggle="dropdown">
                            Filter
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item">Available</a>
                            <a class="dropdown-item">On Sale</a>
                            <a class="dropdown-item">All-terrain</a>
                            <a class="dropdown-item">Electric Motor</a>
                        </div>
                    </div>
                </th>
                <th scope="col"><h4>Store</h4></th>
                <th scope="col"><h4>Style</h4></th>
                <th scope="col"><h4>Electric Motor</h4></th>
                <th scope="col"><h4>All Terrain Suspension</h4></th>
            </tr>
        </thead>
        <tbody>
        @foreach (Bike bike in Model)
        {
            bool hasElectricMotor = bike?.ElectricMotor ?? false;
            bool hasAllTerrain = bike?.AllTerrainSuspension ?? false;
            string bikeRowClass = bike.Available ? "table-default" : "table-warning";
            string bikeButtonClass = bike.Available ? "btn-success" : "btn-warning";
            string bikeButtonText = bike.Available ? "Reserve Now!" : "Check availability";

        <tr class="@bikeRowClass">
            <th scope="row">
                <a class="btn @bikeButtonClass rounded-pill"
                   asp-controller="Reservation" asp-route-id="@bike.Id">
                    <span class="badge badge-light">$@bike.Price/d</span>
                    <strong>@bikeButtonText</strong>
                </a>
            </th>
            <td>@(bike.OwningStore?.Name ?? "???")</td>
            <td>@bike.BikeStyle</td>
            <td>@(hasElectricMotor ? "Yes" : "No")</td>
            <td>@(hasAllTerrain ? "Yes" : "No")</td>
        </tr>
        }
        </tbody>
    </table>
    }
    else
    {
        <h1 class="text-center">No bikes available, <strong>go away</strong></h1>
    }
</div>

CustomerSite/Views/Reservation/Index.cshtml
@model Bike
@addTagHelper *, CustomerSite
@{
    string reserveButtonClass = Model.Available ? "btn-success" : "btn-warning";
    string reserveButtonText = Model.Available ? "Reserve Now!" : "Check Availability";
    bool hasAllTerrain = Model.AllTerrainSuspension ?? false;
    bool hasElectric = Model.ElectricMotor ?? false;
    bool invalidSubmission = (bool?)TempData["InvalidSubmit"] ?? false;
}

<div class="row align-items-center">
    <div class="col-8">
        <div class="carousel slide" data-ride="carousel" id="bikeCarousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="https://via.placeholder.com/700x400/FFB6C1/000000" class="img-fluid" />
                </div>
                <div class="carousel-item">
                    <img src="https://via.placeholder.com/700x400/87CEFA/000000" class="img-fluid" />
                </div>
                <div class="carousel-item">
                    <img src="https://via.placeholder.com/700x400/B0C4DE/000000" class="img-fluid" />
                </div>
            </div>
            <a class="carousel-control-prev" href="#bikeCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#bikeCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
    <div class="col">
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th colspan="2">Bike Title Here</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">All terrain</th>
                    <td>@(hasAllTerrain ? "Yes" : "No")</td>
                </tr>
                <tr>
                    <th scope="row">Electric motor</th>
                    <td>@(hasElectric ? "Yes" : "No")</td>
                </tr>
                <tr>
                    <th scope="row">Frame size</th>
                    <td>@Model.FrameSize</td>
                </tr>
                <tr>
                    <th scope="row">Style</th>
                    <td>@Model.BikeStyle</td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="2">
                        <button type="button" data-toggle="modal" data-target="#reserveButtonModal"
                                class="btn @reserveButtonClass rounded-pill">
                            <strong>@reserveButtonText</strong>
                        </button>
                        <h3>$@Model.Price/day </h3>
                    </th>
                </tr>
            </tfoot>
        </table>
        @if (invalidSubmission)
        {
            <em class="text-danger">Invalid form submission, try again</em>
        }
    </div>
</div>

<div class="modal fade" id="reserveButtonModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            @if (Model.Available)
            {
            <div class="modal-header">
                <h5 class="modal-title">
                    Please fill out the information below
                </h5>
            </div>
            <div class="modal-body">
                <form asp-action="CreateReservation" method="post" id="reservationForm">
                    <vc:reservation-form bike-id="@Model.Id" />
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" form="reservationForm" class="btn btn-primary">Submit 🚲</button>
            </div>
            }
            else
            {
            <div class="modal-header">
                <h5 class="modal-title">
                    Availability
                </h5>
            </div>
            <div class="modal-body">
                <vc:availability-check bike-id="@Model.Id" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close :(</button>
            </div>
            }
        </div>
    </div>
</div>

@*https://placeholder.com/ - place holder images
    https://www.bootdey.com/snippets/view/product-full-detail#preview example product page*@

CustomerSite/Views/Reservation/ReservationAlreadyExists.cshtml
@model Bike

<h1 class="display-3 text-left">Sorry!</h1>
<h2>A reservation is still out for this bike. (┬┬﹏┬┬)</h2>

CustomerSite/Views/Reservation/ReservationConfirmed.cshtml
@model Reservation

<h2 class="text-center">Thank you, @Model.Customer.FirstName!</h2>
<p class="text-center">
    Your reservation for bike @Model.BikeId has been requested.
    An email with reservation details has been sent to <em>@Model.Customer.EmailAddress</em>
</p>
<p class="text-center">
    <strong>
        Your card has been charged @Model.GrandTotal.ToString("C2")
    </strong>
</p>
<p class="text-center">
    Please return <em>no later than</em> @Model.DateDue.ToShortDateString() to avoid late penalty
</p>
<p class="text-center">
    <a asp-controller="Home" asp-action="Index"
        class="btn btn-primary rounded-pill">
        <strong>Home</strong>
    </a>
</p>

CustomerSite/Views/Shared/Components/AvailabilityCheck/Default.cshtml
@model Reservation

@if (Model?.DateDue < DateTime.Now)
{
<p>
    We apologize, this bike seems to be late! <span class="bg-warning"><em>Please check back soon.</em></span>  (╯°□°）╯︵ ┻━┻
</p>
}
else
{
<p>
    Please check back <span class="bg-warning"><em>after @Model?.DateDue.ToShortDateString()</em></span> ⏰
</p>
}

CustomerSite/Views/Shared/Components/ReservationForm/Default.cshtml
@model Services.Reservations.ReservationRequest 

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<input hidden asp-for="RequestedBikeId" />
<div class="form-group">
    <label asp-for="Customer.FirstName">First Name</label>
    <input class="form-control" asp-for="Customer.FirstName" placeholder="John"/>
    <span asp-validation-for="Customer.FirstName" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Customer.LastName">Last Name</label>
    <input class="form-control" asp-for="Customer.LastName" placeholder="Doe"/>
    <span asp-validation-for="Customer.LastName" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Customer.PhoneNumber">Phone</label>
    <input class="form-control" asp-for="Customer.PhoneNumber" placeholder="###-####"/>
    <span asp-validation-for="Customer.PhoneNumber" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Customer.EmailAddress">Email</label>
    <input class="form-control" asp-for="Customer.EmailAddress" placeholder="john_doe@example.com"/>
    <span asp-validation-for="Customer.EmailAddress" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="DaysRequested">How many days would you like to rent? (Max 30)</label>
    <input class="form-control" asp-for="DaysRequested" value="1" min="1" max="30" />
</div>

CustomerSite/Views/Shared/_Layout.cshtml
@{
    string BrandName = "Bike Rental Agency";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @BrandName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">@BrandName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Privacy">
                                Privacy
                            </a>
                        </li>
                        <li>
                            <button id="btnShowModal" data-toggle="modal" data-target="#loginModal" type="button" class="btn btn-dark mr-2">
                                Sign In
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @*Sign in modal*@
            <div class="modal fade" tabindex="-1" id="loginModal"
                 data-keyboard="false" data-backdrop="static">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            Log in
                        </div>
                        <div class="modal-body">
                            <form>
                                <div class="form-group">
                                    <input class="form-control" type="text"
                                           placeholder="Username" id="inputUserName" />
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password"
                                           type="password" id="inputPassword" />
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <a type="button" class="btn btn-dark" asp-controller="Reservation" asp-action="Index">
                                Sign In
                            </a>
                            <button type="button" class="btn btn-dark" data-dismiss="modal">
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-light">
            &copy; 2021 - @BrandName -
            <a asp-controller="Home"
               asp-action="Privacy">
                Privacy
            </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>