EmployeeSite/Models/ErrorViewModel.cs
namespace EmployeeSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployeeSite/Controllers/BikeController.cs
using BikeRentalApi.Models;
using EmployeeSite.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Repositories;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace EmployeeSite.Controllers
{
    public class BikeController : Controller
    {
        readonly IRepositoryAsync<Bike> _bikeRepo;

        public BikeController(IRepositoryAsync<Bike> bike)
        {
            _bikeRepo = bike;
        }
        // GET: BikeController
        public async Task<IActionResult> Index()
        {
            IEnumerable<Bike> bike = await _bikeRepo.GetAsync(BikeRentalRoute.Bikes);
            return View(bike);
        }
        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("StoreId,JobTitle,FirstName,LastName,PhoneNumber")] Bike bike)
        {
            if (!ModelState.IsValid)
            {
                TempData["InvalidSubmit"] = true;
                return View(nameof(Index), bike);
            }
            bike = await _bikeRepo.InsertAsync(bike, BikeRentalRoute.Bikes);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public async Task<IActionResult> Delete(int id)
        {
            Bike bike = await _bikeRepo.GetAsync(id, BikeRentalRoute.Bikes);
            if (bike == null)
                return NotFound();

            await _bikeRepo.DeleteAsync(id, BikeRentalRoute.Bikes);

            return RedirectToAction(nameof(Index));

        }
    }
}

EmployeeSite/Controllers/EmployeeController.cs
using BikeRentalApi.Models;
using EmployeeSite.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Repositories;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace EmployeeSite.Controllers
{
    public class EmployeeController : Controller
    {
        readonly IRepositoryAsync<Employee> _empRepo;

        public EmployeeController(IRepositoryAsync<Employee> emp)
        {
            _empRepo = emp;
        }
        // GET: Employee
        public async Task<IActionResult> Index()
        {
            IEnumerable<Employee> emp = await _empRepo.GetAsync(BikeRentalRoute.Employees);
            return View(emp);
        }
        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("JobTitle,FirstName,LastName,Emailaddress,PhoneNumberStoreId,SupervisorId")] Employee emp)
        {
            if (!ModelState.IsValid)
            {
                TempData["InvalidSubmit"] = true;
                return View(nameof(Index), emp);
            }
            emp = await _empRepo.InsertAsync(emp, BikeRentalRoute.Employees);
            return View("Employee created", emp);
        }
        public IActionResult Edit()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public async Task<IActionResult> Delete(int id)
        {
            Employee employee = await _empRepo.GetAsync(id, BikeRentalRoute.Employees);
            if (employee == null)
                return NotFound();

            await _empRepo.DeleteAsync(id, BikeRentalRoute.Employees);

            return RedirectToAction(nameof(Index));

        }
    }
}

EmployeeSite/Controllers/HomeController.cs
using EmployeeSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace EmployeeSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeeSite/Controllers/StoreController.cs
using BikeRentalApi.Models;
using EmployeeSite.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Repositories;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace EmployeeSite.Controllers
{
    public class StoreController : Controller
    {
        readonly IRepositoryAsync<BikeStore> _storeRepo;

        public StoreController(IRepositoryAsync<BikeStore> store)
        {
            _storeRepo = store;
        }
        // GET: BikeController
        public async Task<IActionResult> Index()
        {
            IEnumerable<BikeStore> store = await _storeRepo.GetAsync(BikeRentalRoute.BikeStores);
            return View(store);
        }
        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public async Task<IActionResult> Delete(int id)
        {
            BikeStore bikeStore = await _storeRepo.GetAsync(id, BikeRentalRoute.BikeStores);
            if (bikeStore == null)
                return NotFound();

            await _storeRepo.DeleteAsync(id, BikeRentalRoute.BikeStores);

            return RedirectToAction(nameof(Index));
        }
    }
}

EmployeeSite/Views/Bike/Create.cshtml
@model BikeRentalApi.Models.Bike
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-horizontal">
    <h4>Reservation</h4>
    <hr />

    <div class="form-group">
        @Html.LabelFor(model => model.FrameSize, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FrameSize, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FrameSize, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ElectricMotor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ElectricMotor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ElectricMotor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AllTerrainSuspension, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AllTerrainSuspension, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AllTerrainSuspension, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BikeStyle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BikeStyle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BikeStyle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OwningStoreId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OwningStoreId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OwningStoreId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Available, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" method="post" class="font-weight-bold">
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>  

EmployeeSite/Views/Bike/Edit.cshtml
@model BikeRentalApi.Models.Bike

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="OwningStore" class="control-label"></label>
                <input asp-for="OwningStore" class="form-control" />
                <span asp-validation-for="OwningStore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FrameSize" class="control-label"></label>
                <input asp-for="FrameSize" class="form-control" />
                <span asp-validation-for="FrameSize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ElectricMotor" class="control-label"></label>
                <input asp-for="ElectricMotor" class="form-control" />
                <span asp-validation-for="ElectricMotor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AllTerrainSuspension" class="control-label"></label>
                <input asp-for="AllTerrainSuspension" class="form-control" />
                <span asp-validation-for="AllTerrainSuspension" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Available" class="control-label"></label>
                <input asp-for="Available" class="form-control" />
                <span asp-validation-for="Available" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BikeStyle" class="control-label"></label>
                <input asp-for="BikeStyle" class="form-control" />
                <span asp-validation-for="BikeStyle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EmployeeSite/Views/Bike/Index.cshtml
@model IEnumerable<Bike>
@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    
    <h1 class="display-4 pb-4">Welcome To the Bike Rental Agency!</h1>
    <div class="text-left">
        <h3>Browse: </h3>
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <form asp-controller="Bike" asp-action="Index">
            <p>
                Customer: <input type="text"/>
                <input type="submit" value="Filter" />
            </p>
        </form>
    </div>
    @if (Model != null)
    {
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col">Id</th>
                    <th scope="col">Frame Size</th>
                    <th scope="col">Bike Style</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Bike bike in Model)
                {
                <tr>
                    <th scope="row">
                        <a asp-controller="Bike" asp-action="Edit" asp-route-id="@bike.Id">
                            Edit
                        </a>
                    </th>
                    <th scope="row">
                        <a asp-action="Delete" asp-route-id="@bike.Id">
                            Delete
                        </a>
                    </th>
                    <td>@bike.Id</td>
                    <td>@bike.FrameSize</td>
                    <td>@bike.BikeStyle</td>
                    <td>@bike.Price</td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h3 class="text-center">There are no bikes!</h3>
    }
</div>

EmployeeSite/Views/Home/Index.cshtml
@model IEnumerable<Reservation>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <h1 class="display-4 pb-4">Welcome To the Bike Rental Agency!</h1>
    <div class="text-left">
        <div class="d-flex flex-row justify-content-end p-3">
            <div>
                <button id="btnShowModal" type="button" class="btn btn-dark mr-2">Sign In</button>
                <div class="modal fade" tabindex="-1" id="loginModal"
                     data-keyboard="false" data-backdrop="static">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">
                                    ×
                                </button>
                            </div>
                            <div class="modal-body">
                                <form>
                                    <div class="form-group">
                                        <input class="form-control" type="text"
                                               placeholder="Login Username" id="inputUserName" />
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control" placeholder="Login Password"
                                               type="password" id="inputPassword" />
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <a type="button" class="btn btn-dark" asp-controller="Reservation" asp-action="Index">
                                    Sign In
                                </a>
                                <button type="button" id="btnHideModal" class="btn btn-dark">
                                    Hide
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a asp-controller="Home" asp-action="Registration" class="btn btn-dark">Register</a>
        </div>
    </div>
</div>

EmployeeSite/Views/Reservation/Create.cshtml
@model BikeRentalApi.Models.Reservation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Reservation</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BikeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BikeId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BikeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CurrentStoreId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CurrentStoreId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CurrentStoreId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateReserved, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateReserved, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateReserved, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateDue, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateDue, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateDue, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateReturned, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateReturned, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateReturned, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GrandTotal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GrandTotal, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GrandTotal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Archive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Archive, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Archive, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a asp-action="Create" class="font-weight-bold">Create</a>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>  

EmployeeSite/Views/Reservation/Edit.cshtml
@model BikeRentalApi.Models.Reservation

@{
    ViewData["Title"] = "Edit";
}

<h4>Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BikeId" class="control-label"></label>
                <select asp-for="BikeId" class="form-control" asp-items="ViewBag.BikeId"></select>
                <span asp-validation-for="BikeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CurrentStoreId" class="control-label"></label>
                <select asp-for="CurrentStoreId" class="form-control" asp-items="ViewBag.CurrentStoreId"></select>
                <span asp-validation-for="CurrentStoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Archive" class="control-label"></label>
                <input asp-for="Archive" class="form-control" />
                <span asp-validation-for="Archive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateReserved" class="control-label"></label>
                <input asp-for="DateReserved" class="form-control" />
                <span asp-validation-for="DateReserved" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDue" class="control-label"></label>
                <input asp-for="DateDue" class="form-control" />
                <span asp-validation-for="DateDue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateReturned" class="control-label"></label>
                <input asp-for="DateReturned" class="form-control" />
                <span asp-validation-for="DateReturned" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GrandTotal" class="control-label"></label>
                <input asp-for="GrandTotal" class="form-control" />
                <span asp-validation-for="GrandTotal" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EmployeeSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeSite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="">Reservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bike" asp-action="">Bikes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="">Stores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EmployeeSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            $("#btnShowModal").click(function () {
                $("#loginModal").modal('show');
            });

            $("#btnHideModal").click(function () {
                $("#loginModal").modal('hide');
            });
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EmployeeSite/Views/Store/Edit.cshtml
@model BikeRentalApi.Models.BikeStore

@{ 
    ViewData["Title"] = "Edit";
}

<h4>BikeStore</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DailyRate" class="control-label"></label>
                <input asp-for="DailyRate" class="form-control" />
                <span asp-validation-for="DailyRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EmployeeSite/Views/Store/Index.cshtml
@model IEnumerable<BikeStore>
@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    
    <h1 class="display-4 pb-4">Welcome To the Bike Rental Agency!</h1>
    <div class="text-left">
        <h3>Browse: </h3>
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <form asp-controller="Home" asp-action="Index">
            <p>
                Customer: <input type="text"/>
                <input type="submit" value="Filter" />
            </p>
        </form>
    </div>
    @if (Model != null)
    {
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col">Name</th>
                    <th scope="col">Phone Number</th>
                    <th scope="col">Hourly Rate</th>
                    <th scope="col">Discount</th>
                    <th scope="col">Latitude</th>
                    <th scope="col">Longitude</th>
                </tr>
            </thead>
            <tbody>
                @foreach (BikeStore store in Model)
                {
                <tr>
                    <th scope="row">
                        <a asp-controller="Store" asp-action="Edit" asp-route-id="@store.Id">
                            Edit
                        </a>
                    </th>
                    <th scope="row">
                        <a asp-action="Delete" asp-route-id="@store.Id">
                            Delete
                        </a>
                    </th>
                    <td>@store.Name</td>
                    <td>@store.PhoneNumber</td>
                    <td>@store.DailyRate</td>
                    <td>@store.Discount</td>
                    <td>@store.Latitude</td>
                    <td>@store.Longitude</td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h3 class="text-center">There are no reservations! No money for you!</h3>
    }
</div>